require "skippr/version"

require 'active_resource'
require "skippr/active_resource/base"

require "skippr/exceptions"
require "skippr/api"


require "skippr/resources/account"
require "skippr/resources/attachment"
require "skippr/resources/attachment_type"
require "skippr/resources/bank_account"
require "skippr/resources/case"
require "skippr/resources/case_entry"
require "skippr/resources/customer"
require "skippr/resources/customer_state"
require "skippr/resources/employee"
require "skippr/resources/event"
require "skippr/resources/facility"
require "skippr/resources/invoice"
require "skippr/resources/invoice_position"
require "skippr/resources/item"
require "skippr/resources/item_category"
require "skippr/resources/item_order"
require "skippr/resources/offer"
require "skippr/resources/service_type"
require "skippr/resources/supplier"
require "skippr/resources/task"
require "skippr/resources/unit"
require "skippr/resources/user"
